server.port=5050
spring.mongodb.uri=mongodb://localhost:27017/cloudshare
spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://together-camel-32.clerk.accounts.dev
clerk.jwks-url=https://together-camel-32.clerk.accounts.dev/.well-known/jwks.json

#file Upload Configuration
spring.servlet.multipart.max-file-size=5mb
spring.servlet.multipart.max-request-size=50mb
